# Generated by Django 5.2.8 on 2025-12-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_postattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='postattachment',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='file',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
