worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;
    client_max_body_size 25M;

    # нужно для WebSocket
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    # ---------------------------
    # HTTP → HTTPS редирект
    # ---------------------------
    server {
        listen 80;
        server_name germify.ddns.net;
        return 301 https://$host$request_uri;
    }

    # ---------------------------
    # HTTPS сервер (Django ASGI)
    # ---------------------------
    server {
        listen 443 ssl;
        server_name germify.ddns.net;

        ssl_certificate     "C:/Program Files/win-acme/germify/germify.ddns.net-chain.pem";
        ssl_certificate_key "C:/Program Files/win-acme/germify/germify.ddns.net-key.pem";

        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout 5m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        # STATIC
	location /static/ {
    		alias C:/gerychhh_/germify/germify/backend/core/static/;
	}


        # MEDIA
        location /media/ {
            alias C:/gerychhh_/germify/germify/backend/media/;
            add_header Accept-Ranges bytes;
        }

        # ---- WebSocket (Channels) ----
        # Важно: проксируем на ASGI-порт (например 8001)
        location /ws/ {
            proxy_pass http://host.docker.internal:8001;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 3600;
        }

        # ---- Всё остальное (HTTP) ----
        location / {
            proxy_pass http://127.0.0.1:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
