# Generated by ChatGPT on 2025-12-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_postattachment_file_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="Название")),
                ("slug", models.SlugField(allow_unicode=True, blank=True, max_length=90, unique=True, verbose_name="Ссылка")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("icon", models.ImageField(blank=True, null=True, upload_to="community_icons/", verbose_name="Иконка")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_communities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CommunityMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_admin", models.BooleanField(default=False, verbose_name="Администратор")),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="Вступил")),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.community",
                        verbose_name="Сообщество",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
                "unique_together": {("community", "user")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="core.community",
                verbose_name="Сообщество",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="as_community",
            field=models.BooleanField(default=False, verbose_name="Опубликовать от лица сообщества"),
        ),
    ]
