# Generated by ChatGPT on 2025-12-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_community_and_membership_and_post_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("dm", "Личные"), ("group", "Группа")], default="dm", max_length=16, verbose_name="Тип")),
                ("title", models.CharField(blank=True, max_length=120, verbose_name="Название")),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="chat_avatars/", verbose_name="Аватар")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("last_message_at", models.DateTimeField(blank=True, null=True, verbose_name="Последнее сообщение")),
                ("last_message_id", models.BigIntegerField(blank=True, null=True, verbose_name="ID последнего сообщения")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_chats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "dm_user1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dm_chats_as_user1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь 1",
                    ),
                ),
                (
                    "dm_user2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dm_chats_as_user2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь 2",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ChatMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("owner", "Владелец"), ("admin", "Администратор"), ("member", "Участник")], default="member", max_length=16, verbose_name="Роль")),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="Вступил")),
                ("unread_count", models.PositiveIntegerField(default=0, verbose_name="Непрочитано")),
                ("last_read_message_id", models.BigIntegerField(blank=True, null=True, verbose_name="ID последнего прочитанного")),
                ("is_hidden", models.BooleanField(default=False, verbose_name="Скрыт")),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.chat",
                        verbose_name="Чат",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
                "unique_together": {("chat", "user")},
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Текст")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("edited_at", models.DateTimeField(blank=True, null=True, verbose_name="Изменено")),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chat",
                        verbose_name="Чат",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="chat",
            constraint=models.UniqueConstraint(fields=("dm_user1", "dm_user2"), name="unique_dm_pair"),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(fields=["kind", "last_message_at"], name="chat_kind_last_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["chat", "created_at"], name="chat_msg_chat_created_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["chat", "id"], name="chat_msg_chat_id_idx"),
        ),
    ]
