# Generated by ChatGPT on 2025-12-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_migrate_messages_to_chats"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessageAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="attachments/", verbose_name="Файл")),
                ("original_name", models.CharField(blank=True, max_length=255, verbose_name="Оригинальное имя файла")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.chatmessage",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="chatmessageattachment",
            index=models.Index(fields=["message", "id"], name="chat_msg_att_msg_idx"),
        ),
    ]
