# Generated by Django 5.2.9 on 2025-12-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_chatmessageattachment'),
    ]

    operations = [
    ]
